name: 'size'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 7.1.7
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - uses: posva/size-check-action@v1.1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: build:size
          files: packages/router/dist/vue-router.global.prod.js packages/size-checks/dist/webRouter.js
